### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/mylinks#10]
error when trying to install:

> Unable to install mylinks. Error(s):
> Installing My Links
> Failed to execute xoops_module_pre_install_mylinks
> YOUR XOOPS VERSION MUST BE UPGRADED TO AT LEAST VERSION 2.5.8 TO USE THIS MODULE

XOOPS 2.5.11-Beta1
PHP Version  7.3.12

**Comment by mambax7** [comment]
This should fix it: https://github.com/XoopsModules25x/mylinks/commit/eefcac23269c331c45f72edb9708da4f1662240e
